### ISSUE TITLE
使用WeChatSpellBook框架会出现空指针问题

### ISSUE THREAD

**Issue by Rindiaco** [Gh0u1L5/WechatSpellbook#22]
10-08 14:15:12.378 11021-11060/? E/Xposed: kotlin.KotlinNullPointerException
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Classes$MsgInfoStorage$2.invoke(Classes.kt:22)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Classes$MsgInfoStorage$2.invoke(Classes.kt:12)
        at com.gh0u1l5.wechatmagician.spellbook.WechatGlobal$wxLazy$2.invoke(WechatGlobal.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Classes.getMsgInfoStorage(Classes.kt)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Methods$MsgInfoStorage_insert$2.invoke(Methods.kt:16)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Methods$MsgInfoStorage_insert$2.invoke(Methods.kt:12)
        at com.gh0u1l5.wechatmagician.spellbook.WechatGlobal$wxLazy$2.invoke(WechatGlobal.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Methods.getMsgInfoStorage_insert(Methods.kt)
        at com.gh0u1l5.wechatmagician.spellbook.hookers.Storage$onMessageStorageInsertHooker$1.invoke(Storage.kt:42)
        at com.gh0u1l5.wechatmagician.spellbook.hookers.Storage$onMessageStorageInsertHooker$1.invoke(Storage.kt:16)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:50)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$2.invoke(XposedUtil.kt:35)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$2.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil$tryAsynchronously$1.invoke(BasicUtil.kt:33)
        at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil$tryAsynchronously$1.invoke(BasicUtil.kt:9)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by yuxia761** [comment]
我也出现空指针
2018-10-30 17:59:41.822 18987-19275/? E/Xposed: kotlin.KotlinNullPointerException
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.Classes$MMBaseAdapter$2.invoke(Classes.kt:25)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.Classes$MMBaseAdapter$2.invoke(Classes.kt:11)
        at com.gh0u1l5.wechatmagician.spellbook.WechatGlobal$wxLazy$2.invoke(WechatGlobal.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.Classes.getMMBaseAdapter(Unknown Source:7)
        at com.gh0u1l5.wechatmagician.spellbook.hookers.ListViewHider$MMBaseAdapterHooker$1.invoke(ListViewHider.kt:86)
        at com.gh0u1l5.wechatmagician.spellbook.hookers.ListViewHider$MMBaseAdapterHooker$1.invoke(ListViewHider.kt:17)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:50)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil.tryVerbosely(BasicUtil.kt:21)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.tryHook(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.access$tryHook(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1.run(XposedUtil.kt:45)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:187)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2018-10-30 17:59:41.823 18987-19275/? E/Xposed: kotlin.KotlinNullPointerException
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.base.Classes$MMListPopupWindow$2.invoke(Classes.kt:10)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.base.Classes$MMListPopupWindow$2.invoke(Classes.kt:8)
        at com.gh0u1l5.wechatmagician.spellbook.WechatGlobal$wxLazy$2.invoke(WechatGlobal.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.base.Classes.getMMListPopupWindow(Unknown Source:7)
        at com.gh0u1l5.wechatmagician.spellbook.hookers.MenuAppender$onMMListPopupWindowShowHooker$1.invoke(MenuAppender.kt:50)
        at com.gh0u1l5.wechatmagician.spellbook.hookers.MenuAppender$onMMListPopupWindowShowHooker$1.invoke(MenuAppender.kt:21)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:50)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil.tryVerbosely(BasicUtil.kt:21)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.tryHook(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.access$tryHook(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1.run(XposedUtil.kt:45)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:187)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2018-10-30 17:59:41.824 18987-19275/? E/Xposed: kotlin.KotlinNullPointerException
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.base.Classes$MMListPopupWindow$2.invoke(Classes.kt:10)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.base.Classes$MMListPopupWindow$2.invoke(Classes.kt:8)
        at com.gh0u1l5.wechatmagician.spellbook.WechatGlobal$wxLazy$2.invoke(WechatGlobal.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.ui.base.Classes.getMMListPopupWindow(Unknown Source:7)
        at com.gh0u1l5.wechatmagician.spellbook.hookers.MenuAppender$onMMListPopupWindowDismissHooker$1.invoke(MenuAppender.kt:69)
        at com.gh0u1l5.wechatmagician.spellbook.hookers.MenuAppender$onMMListPopupWindowDismissHooker$1.invoke(MenuAppender.kt:21)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:50)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil.tryVerbosely(BasicUtil.kt:21)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.tryHook(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.access$tryHook(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1.run(XposedUtil.kt:45)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:187)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2018-10-30 17:59:41.825 18987-19275/? E/Xposed: kotlin.KotlinNullPointerException
        at com.blanke.wechatbotxposed.hook.Classes$ChattingFooterEventImpl$2.invoke(Classes.kt:13)
        at com.blanke.wechatbotxposed.hook.Classes$ChattingFooterEventImpl$2.invoke(Classes.kt:10)
        at com.gh0u1l5.wechatmagician.spellbook.WechatGlobal$wxLazy$2.invoke(WechatGlobal.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at com.blanke.wechatbotxposed.hook.Classes.getChattingFooterEventImpl(Unknown Source:7)
        at com.blanke.wechatbotxposed.hook.SendMsgHooker$chattingFooterEventImplHook$1.invoke(SendMsgHooker.kt:46)
        at com.blanke.wechatbotxposed.hook.SendMsgHooker$chattingFooterEventImplHook$1.invoke(SendMsgHooker.kt:8)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:50)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil.tryVerbosely(BasicUtil.kt:21)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.tryHook(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.access$tryHook(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1.run(XposedUtil.kt:45)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:187)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2018-10-30 17:59:41.826 18987-19275/? E/Xposed: kotlin.KotlinNullPointerException
        at com.blanke.wechatbotxposed.hook.Classes$NetSceneSendMsg$2.invoke(Classes.kt:21)
        at com.blanke.wechatbotxposed.hook.Classes$NetSceneSendMsg$2.invoke(Classes.kt:10)
        at com.gh0u1l5.wechatmagician.spellbook.WechatGlobal$wxLazy$2.invoke(WechatGlobal.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at com.blanke.wechatbotxposed.hook.Classes.getNetSceneSendMsg(Unknown Source:7)
        at com.blanke.wechatbotxposed.hook.SendMsgHooker$netSceneSendMsgHook$1.invoke(SendMsgHooker.kt:18)
        at com.blanke.wechatbotxposed.hook.SendMsgHooker$netSceneSendMsgHook$1.invoke(SendMsgHooker.kt:8)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:50)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil.tryVerbosely(BasicUtil.kt:21)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.tryHook(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.access$tryHook(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1.run(XposedUtil.kt:45)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:187)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2018-10-30 17:59:41.827 18987-19275/? E/Xposed: kotlin.KotlinNullPointerException
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Methods$MsgInfoStorage_insert$2.invoke(Methods.kt:15)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Methods$MsgInfoStorage_insert$2.invoke(Methods.kt:12)
        at com.gh0u1l5.wechatmagician.spellbook.WechatGlobal$wxLazy$2.invoke(WechatGlobal.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Methods.getMsgInfoStorage_insert(Unknown Source:7)
        at com.gh0u1l5.wechatmagician.spellbook.hookers.Storage$onMessageStorageInsertHooker$1.invoke(Storage.kt:42)
        at com.gh0u1l5.wechatmagician.spellbook.hookers.Storage$onMessageStorageInsertHooker$1.invoke(Storage.kt:16)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:50)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil.tryVerbosely(BasicUtil.kt:21)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.tryHook(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.access$tryHook(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1.run(XposedUtil.kt:45)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:187)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2018-10-30 17:59:41.827 18987-19275/? E/Xposed: kotlin.KotlinNullPointerException
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Methods$MsgInfoStorage_insert$2.invoke(Methods.kt:15)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Methods$MsgInfoStorage_insert$2.invoke(Methods.kt:12)
        at com.gh0u1l5.wechatmagician.spellbook.WechatGlobal$wxLazy$2.invoke(WechatGlobal.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at com.gh0u1l5.wechatmagician.spellbook.mirror.com.tencent.mm.storage.Methods.getMsgInfoStorage_insert(Unknown Source:7)
        at com.gh0u1l5.wechatmagician.spellbook.hookers.Storage$onMessageStorageInsertHooker$1.invoke(Storage.kt:42)
        at com.gh0u1l5.wechatmagician.spellbook.hookers.Storage$onMessageStorageInsertHooker$1.invoke(Storage.kt:16)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:50)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$tryHook$1.invoke(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.BasicUtil.tryVerbosely(BasicUtil.kt:21)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.tryHook(XposedUtil.kt:34)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil.access$tryHook(XposedUtil.kt:14)
        at com.gh0u1l5.wechatmagician.spellbook.util.XposedUtil$postHooker$1.run(XposedUtil.kt:45)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:187)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by Rindiaco** [comment]
貌似是因为微信版本不一样所以劫持的方法的方法找不到了

**Comment by skys215** [comment]
我也出现了NullPointerException。不过是Preference.kt，BaseUtil tryAsynchornously那里。
